### ISSUE TITLE
[Bug]: lateinit property credential has not been initialized

### ISSUE THREAD

**Issue by daiyam** [vedantmgoyal2009/winget-releaser#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

From the latest run (https://github.com/VSCodium/vscodium/actions/runs/4498341084/jobs/7918745356), I get the following error:
```
Executing command: java -jar komac.jar update --id 'VSCodium.VSCodium.Insiders' --version 1.77.0.23082 --urls 'https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-arm64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-ia32-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-x64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-arm64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-ia32-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-x64-1.77.0.23082-insider.exe' --submit
  Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property credential has not been initialized
  	at token.windows.CredAdvapi32$PCREDENTIAL.getCredential(CredAdvapi32.kt:158)
  	at token.windows.CredManagerBackedSecureStore.get-AcNMXiM(CredManagerBackedSecureStore.kt:75)
  	at token.TokenStore.<init>(TokenStore.kt:13)
  	at commands.NewManifest.<init>(NewManifest.kt:58)
  	at MainKt.main(Main.kt:14)
  node:internal/errors:841
    const err = new Error(message);
                ^
  
  Error: Command failed: & $env:JAVA_HOME_17_X64\bin\java.exe -jar komac.jar update --id 'VSCodium.VSCodium.Insiders' --version 1.77.0.[23](https://github.com/VSCodium/vscodium/actions/runs/4498341084/jobs/7918745356#step:4:24)082 --urls 'https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-arm64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-ia32-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumSetup-x64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-arm64-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-ia32-1.77.0.23082-insider.exe,https://github.com/VSCodium/vscodium-insiders/releases/download/1.77.0.23082-insider/VSCodiumUserSetup-x64-1.77.0.23082-insider.exe' --submit
      at checkExecSyncError (node:child_process:8[28](https://github.com/VSCodium/vscodium/actions/runs/4498341084/jobs/7918745356#step:4:29):11)
      at execSync (node:child_process:899:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:77:39
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 5664,
    stdout: null,
    stderr: null
  }
```

@russellbanks Can it be an issue of Komac?

**Comment by vedantmgoyal9** [comment]
Fixed in https://github.com/russellbanks/Komac/releases/tag/v1.3.1.
