### ISSUE TITLE
[Bug]: RequestError [HttpError]: Bad credentials

### ISSUE THREAD

**Issue by sn4k3** [vedantmgoyal2009/winget-releaser#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
Run vedantmgoyal2009/winget-releaser@v2
D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:4285
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:4285:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:9867:13 {
  status: 401,
  response: {
    url: 'https://api.github.com/repos/sn4k3/UVtools/releases/tags/v4.0.2',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 02 Oct 2023 01:14:24 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '1011:854B:4D7[16](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:17)C4:9F7BE56:651A[19](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:20)70',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '59',
      'x-ratelimit-reset': '1696212864',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/sn4k3/UVtools/releases/tags/v4.0.2',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/[20](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:21).5.0 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {
          'api.github.com:443:::::::::::::::::::::': [ [TLSSocket] ]
        },
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/sn4k3/UVtools/actions/runs/6374732694/job/17299697754#step:2:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}

Node.js v20.5.0
```

I tried with new token but still got this problem in every release.
Job: https://github.com/sn4k3/UVtools/blob/master/.github/workflows/package-publish.yml#L16

**Comment by vedantmgoyal9** [comment]
This means you have to regenerate your GitHub Personal Access Token (PAT). Don't forget to update it at https://github.com/sn4k3/UVtools/settings/secrets/actions.

**Comment by sn4k3** [comment]
I always had a PAT configured, this worked before, but now it stop working, I have this:

![image](https://github.com/vedantmgoyal2009/winget-releaser/assets/113281/640095cc-b13b-40e3-8810-b1c72a247020)
![image](https://github.com/vedantmgoyal2009/winget-releaser/assets/113281/7e41c864-d405-4d04-8e11-79778e4b4c0a)

What is wrong?

**Comment by sn4k3** [comment]
I run the workflow with the fix, and it worked to open the PR correctly. However, the action did not finish successfully, but it may not related...

https://github.com/sn4k3/UVtools/actions/runs/6568374542/job/17842688067

```
Run vedantmgoyal2009/winget-releaser@v2
Updating manifests and creating pull request...
Cleaning up previous stale branches of merged pull requests on the fork...
undefined:1
A server error has occurred
^

SyntaxError: Unexpected token 'A', "A server e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.0
```
