### ISSUE TITLE
[Bug]: Actions failed with "RequestError [HttpError]: Not Found".

### ISSUE THREAD

**Issue by sprout2000** [vedantmgoyal2009/winget-releaser#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here's the log:

```sh
Run vedantmgoyal2009/winget-releaser@latest
D:\a\_actions\vedantmgoyal200[9](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5067517923#step:2:10)\winget-releaser\latest\dist\index.js:4235
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Not Found
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:4235:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9700:7 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/sprout2000/leafview/releases/tags/refs%2Ftags%2Fv2.0.4',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 26 Sep 2022 00:34:56 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0401:2C4E:21E5CA7:4357355:6330F3B0',
      'x-oauth-scopes': 'public_repo',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4999',
      'x-ratelimit-reset': '1664156096',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/sprout2000/leafview/releases/tags/refs%2Ftags%2Fv2.0.4',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.13.0 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: [10](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5067517923#step:2:11)00,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5067517923#step:2:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5067517923#step:2:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5067517923#step:2:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}
```

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @sprout2000 for bug

**Comment by sprout2000** [comment]
@vedantmgoyal2009 
Thank you so much for the quick response.
I would be honored to be added to the contributors for bug.

**Comment by vedantmgoyal9** [comment]
Recent workflow runs on other repos are successful. Can you try re-running the workflow?

**Comment by vedantmgoyal9** [comment]
cc @sprout2000

**Comment by sprout2000** [comment]
@vedantmgoyal2009 

Sorry, but still same...

```sh
Run vedantmgoyal2009/winget-releaser@latest
D:\a\_actions\vedantmgoyal200[9](https://github.com/sprout2000/leafview/actions/runs/3139306346/jobs/5099695167#step:2:10)\winget-releaser\latest\dist\index.js:4235
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Not Found
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:4235:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9700:7 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/sprout2000/leafview/releases/tags/refs%2Ftags%2Fv2.0.6',
    status: 404,
```

**Comment by sprout2000** [comment]
with DEBUG logs:

```sh
##[debug]Evaluating condition for step: 'Run vedantmgoyal2009/winget-releaser@latest'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run vedantmgoyal[2](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:2)009/winget-releaser@latest
##[debug]Loading inputs
##[debug]Evaluating: github.ref
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ref'
##[debug]=> 'refs/tags/v2.0.4'
##[debug]Result: 'refs/tags/v2.0.4'
##[debug]Evaluating: secrets.WINGET_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'WINGET_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.repository_owner
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository_owner'
##[debug]=> 'sprout2000'
##[debug]Result: 'sprout2000'
##[debug]Loading env
Run vedantmgoyal2009/winget-releaser@latest
  
D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:42[3](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:3)5
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^
RequestError [HttpError]: Not Found
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:[4](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:4)23[5](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:5):21
    at processTicksAndRejections (node:internal/process/task_queues:9[6](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:6):5)
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9[7](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:7)00:7 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/sprout2000/leafview/releases/tags/refs%2Ftags%2Fv2.0.4',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-[8](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:8)',
      date: 'Tue, 27 Sep 2022 23:21:35 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0400:513C:2E15181:5BE3B[9](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:9)7:6333857F',
      'x-oauth-scopes': 'public_repo',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4999',
      'x-ratelimit-reset': '1664324495',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/sprout2000/leafview/releases/tags/refs%2Ftags%2Fv2.0.4',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.13.0 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: [10](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:10)00,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:443:::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:443:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run vedantmgoyal[20](https://github.com/sprout2000/leafview/actions/runs/3124246506/jobs/5100258468#step:2:20)09/winget-releaser@latest
```

**Comment by vedantmgoyal9** [comment]
https://github.blog/changelog/2022-09-27-github-actions-additional-information-available-in-github-event-payload-for-scheduled-workflow-runs

GitHub has made additional information available in event payload on schedule events. This might help in fixing this bug.

Also mentioning @russellbanks @sitiom

**Comment by sprout2000** [comment]
@vedantmgoyal2009 
Thank you for the directions.
But to be honest, I don't really understand it, so I'll be sending pull requests to winget-pkgs manually for a while.
See you there.

**Comment by sitiom** [comment]
@vedantmgoyal2009 Neovim Winget Releaser action failed with the same error: https://github.com/neovim/neovim/actions/runs/3159879584/jobs/5143885539

**Comment by vedantmgoyal9** [comment]
I've created a PR. Thanks for notifying me. I'm having a hard time these days.
