### ISSUE TITLE
[Bug]: Status 500: RequestError [HttpError]: other side closed

### ISSUE THREAD

**Issue by Gedochao** [vedantmgoyal2009/winget-releaser#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## What's happening

We are getting RequestError [HttpError] when releasing [Scala CLI](https://github.com/VirtusLab/scala-cli) on winget with the `winget-releaser` action.

```
RequestError [HttpError]: other side closed
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:6964:11
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:30094:27 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests%2Fv%2FVirtusLab%2FScalaCLI',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/5.0.1 Node.js/20.8.1 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] },
        [Symbol(kCapture)]: false
      },
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```

We got this error on 2 subsequent releases up till now (details below). 

## Scala CLI tags on which it failed and the related `winget-pckgs` PRs
- https://github.com/VirtusLab/scala-cli/tree/v1.1.2 - Scala CLI `v1.1.2` tag: winget release failed with the error above, PR to `winget-pckgs` got created, it's still hanging
  - the `winget-pckgs` PR: https://github.com/microsoft/winget-pkgs/pull/135148
- https://github.com/VirtusLab/scala-cli/tree/v1.1.1 - Scala CLI `v1.1.1` tag, winget release failed with the error above, PR to `winget-pckgs` got created and then merged, seems to have been a false positive as `v1.1.1` is available on `winget`
  - the `winget-pckgs` PR: https://github.com/microsoft/winget-pkgs/pull/133549
- `v1.1.0` and earlier releases have been green, so the issue started appearing with `v1.1.1`

## Extra context
- https://github.com/VirtusLab/scala-cli/issues/2689 - corresponding Scala CLI issue

**Comment by Gedochao** [comment]
Here's how we use the `winget-releaser` action in our workflow:
https://github.com/VirtusLab/scala-cli/blob/0421cd92116c6276ca658680e172bae255fd95c4/.github/workflows/ci.yml#L1266-L1271

**Comment by mgyucht** [comment]
We're seeing this as well with the Databricks CLI: https://github.com/databricks/cli/blob/main/.github/workflows/release.yml#L121-L131.

Is this a problem from `Cleaning up previous stale branches of merged pull requests on the fork` or `Check for versions w.r.t. max-versions-to-keep`? It's hard to tell from the error message.

**Comment by Gedochao** [comment]
https://github.com/VirtusLab/scala-cli/issues/2689#issuecomment-1983325033
Interestingly, this seems to have fixed itself during our recent release.
Was any work done? Can anyone confirm this is fixed?

**Comment by isaak654** [comment]
I can confirm the issue in the today's release of Sandboxie Plus:
https://github.com/sandboxie-plus/Sandboxie/actions/runs/8425847760/job/23072858860#step:2:89

```
RequestError [HttpError]: other side closed
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:6964:11
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:30094:27 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests%2Fs%2FSandboxie%2FPlus',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/5.0.1 Node.js/20.8.1 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] },
        [Symbol(kCapture)]: false
      },
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```

**Comment by isaak654** [comment]
I can confirm the issue in the today's release of Sandboxie Plus:
https://github.com/sandboxie-plus/Sandboxie/actions/runs/8425847760/job/23072858860#step:2:89

<details>
  <summary>RequestError [HttpError]: other side closed</summary>

```
RequestError [HttpError]: other side closed
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:6964:11
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:30094:27 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests%2Fs%2FSandboxie%2FPlus',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/5.0.1 Node.js/20.8.1 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] },
        [Symbol(kCapture)]: false
      },
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```
</details>

**Comment by grofit** [comment]
Same on todays release of Strem
https://github.com/strem-app/strem/actions/runs/8520086677/job/23335563086

```
RequestError [HttpError]: other side closed
    at D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:6964:11
    at async D:\a\_actions\vedantmgoyal2009\winget-releaser\v2\dist\index.js:30094:27 {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests%2Fs%2FSandboxie%2FPlus',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/5.0.1 Node.js/20.8.1 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: [100](https://github.com/sandboxie-plus/Sandboxie/actions/runs/8425847760/job/23072858860#step:2:103)0,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] },
        [Symbol(kCapture)]: false
      },
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
```

**Comment by OpenWaygate** [comment]
Is there any update about this bug?

**Comment by vedantmgoyal9** [comment]
This has been fixed in `vedantmgoyal9/winget-releaser@main`.

**Comment by isaak654** [comment]
> This has been fixed in `vedantmgoyal9/winget-releaser@main`.

Is `uses: vedantmgoyal9/winget-releaser@v2` still valid in our workflow?

**Comment by vedantmgoyal9** [comment]
@isaak654 the new changes are only available on `vedantmgoyal9/winget-releaser@main`. The v2 will still work, but it won't include the newest changes.

**Comment by vedantmgoyal9** [comment]
@allcontributors
please add @Gedochao for bug.
please add @mgyucht for bug.
please add @grofit for bug.
please add @OpenWaygate for bug.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @grofit forbug

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @grofit for bug

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @OpenWaygate for bug

**Comment by vedantmgoyal9** [comment]
@allcontributors please add grofit for bug
