### ISSUE TITLE
[Bug]: Unknown property 'UpgradeCode'

### ISSUE THREAD

**Issue by dorssel** [vedantmgoyal2009/winget-releaser#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Automatic release run: https://github.com/dorssel/usbipd-win/actions/runs/7765791325/job/21180863349

This worked before (when this action auto-released 4.0.0 on December 6, 2023). This time an exception occurs:

```
Exception in thread "main" UnknownPropertyException at Installers[0].UpgradeCode on line 11, column 3: Unknown property 'UpgradeCode'. Known properties are: AppsAndFeaturesEntries, Architecture, Capabilities, Commands, Dependencies, DisplayInstallWarnings, ElevationRequirement, ExpectedReturnCodes, FileExtensions, InstallLocationRequired, InstallModes, InstallationMetadata, InstallerAbortsTerminal, InstallerLocale, InstallerSha256, InstallerSuccessCodes, InstallerSwitches, InstallerType, InstallerUrl, Markets, MinimumOSVersion, NestedInstallerFiles, NestedInstallerType, PackageFamilyName, Platform, ProductCode, Protocols, ReleaseDate, RequireExplicitUpgrade, RestrictedCapabilities, Scope, SignatureSha256, UnsupportedArguments, UnsupportedOSArchitectures, UpgradeBehavior
```

**Comment by dorssel** [comment]
Turns out https://github.com/microsoft/winget-pkgs/pull/134322 updated the original manifest, in order to *move* UpgradeCode to the AppsAndFeaturesEntries key. But instead it left the original UpgradeCode (under Installers) in tact (whereas it should have been removed there).

Found out by creating a brand new manifest using winget-create, see https://github.com/microsoft/winget-pkgs/pull/137822

**Comment by gerardog** [comment]
Same ocurring with gsudo after microsoft/winget-pkgs#131849 which introduced the `winget install gsudo --installer-type portable` option

See [logs](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470).


```
Run vedantmgoyal[2](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:2)009/winget-releaser@v2
  with:
    token: ***
    identifier: gerardog.gsudo
    installers-regex: \.msi$
    max-versions-to-keep: 0
    release-repository: gsudo
    release-tag: v2.4.4
    fork-user: gerardog
  env:
    version: 2.4.4
    version_MajorMinorPatch: 2.4.4
    is_prerelease: 0
Updating manifests and creating pull request...
  Executing command: java -jar komac.jar update --id 'gerardog.gsudo' --version 2.4.4 --urls 'https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.arm64.msi,https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.x64.msi,https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.x86.msi' --submit
  CI environment detected! Komac will throw errors instead of prompting on invalid input
  Latest version of gerardog.gsudo: 2.4.2
  Exception in thread "main" UnknownPropertyException at Installers[0].UpgradeCode on line 14, column [3](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:3): Unknown property 'UpgradeCode'. Known properties are: AppsAndFeaturesEntries, Architecture, Capabilities, Commands, Dependencies, DisplayInstallWarnings, ElevationRequirement, ExpectedReturnCodes, FileExtensions, InstallLocationRequired, InstallModes, InstallationMetadata, InstallerAbortsTerminal, InstallerLocale, InstallerSha256, InstallerSuccessCodes, InstallerSwitches, InstallerType, InstallerUrl, Markets, MinimumOSVersion, NestedInstallerFiles, NestedInstallerType, PackageFamilyName, Platform, ProductCode, Protocols, ReleaseDate, RequireExplicitUpgrade, RestrictedCapabilities, Scope, SignatureSha256, UnsupportedArguments, UnsupportedOSArchitectures, UpgradeBehavior
  	at com.charleskorn.kaml.YamlObjectInput.decodeElementIndex(YamlObjectInput.kt:52)
  	at schemas.manifest.InstallerManifest$Installer$$serializer.deserialize(InstallerManifest.kt)
  	at schemas.manifest.InstallerManifest$Installer$$serializer.deserialize(InstallerManifest.kt)
  	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
  	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:10[4](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:4))
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
  	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:[5](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:5)33)
  	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
  	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
  	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:3[6](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:6))
  	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
  	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:25[7](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:7))
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
  	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
  	at schemas.manifest.InstallerManifest$$serializer.deserialize(InstallerManifest.kt)
  	at schemas.manifest.InstallerManifest$$serializer.deserialize(InstallerManifest.kt)
  	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
  	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
  	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
  	at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:54)
  	at com.charleskorn.kaml.Yaml.decodeFromStream(Yaml.kt:47)
  	at com.charleskorn.kaml.Yaml.decodeFromStream$default(Yaml.kt:46)
  	at data.PreviousManifestData$installerManifest$1.invokeSuspend(PreviousManifestData.kt:34)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:10[8](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:8))
  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:7[9](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:9)3)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
  node:internal/errors:866
    const err = new Error(message);
                ^
  
  Error: Command failed: & C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.[10](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:10)-7\x64\bin\java -jar komac.jar update --id 'gerardog.gsudo' --version 2.4.4 --urls 'https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.arm64.msi,https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.x64.msi,https://github.com/gerardog/gsudo/releases/download/v2.4.4/gsudo.setup.x86.msi' --submit
      at checkExecSyncError (node:child_process:890:[11](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:11))
      at execSync (node:child_process:962:[15](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:16))
      at D:\a\_actions\vedantmgoyal[20](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:21)09\winget-releaser\v2\dist\index.js:[30](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:31)079:[39](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:40)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: [66](https://github.com/gerardog/gsudo/actions/runs/7967267209/job/21749957470#step:7:67)80,
    stdout: null,
    stderr: null
  }
  
  Node.js v20.8.1
```

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @gerardog for bug

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @dorssel for bug
